version: '3.1' 
services:
#-----------------
 angular:
  build: ./app
  ports:
  - "3535:3535"
#-----------------
 express: 
  build: ./api
  ports:
  - "7777:7777"
  links:
  - database 
#-----------------
 database:
  image: mongo 
  ports:
  - "20207:20207"