version: '0.1' 
services:
#-----------------
 react:
  build: ./app
  ports:
  - "3000:3000"
#-----------------
 express: 
  build: ./api
  ports:
  - "3005:3005"
  links:
  - database 
#-----------------
 database:
  image: amazon/dynamodb-local
  ports:
  - "8000:8000"